export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  VENDOR: "VENDOR",
  VENDOR_STAFF: "VENDOR_STAFF",
  CUSTOMER: "CUSTOMER",
  DELIVERY: "DELIVERY",
  SUPPORT: "SUPPORT",
} as const;